create extension if not exists "pg_cron" with schema "pg_catalog";

drop extension if exists "pg_net";

create type "public"."metodo_pagamento" as enum ('Dinheiro', 'Cartão de Crédito', 'Cartão de Débito', 'Pix', 'A Prazo', 'Crédito Funcionário');

create type "public"."status_pagamento" as enum ('Pendente', 'Pago', 'Vencido');

create type "public"."status_recebimento" as enum ('Pendente', 'Recebido', 'Vencido');

create type "public"."tipo_movimentacao" as enum ('ABERTURA', 'SUPRIMENTO', 'SANGRIA', 'VENDA', 'PAGAMENTO_CONTA', 'RECEBIMENTO_CONTA');


  create table "public"."Clientes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "nome" text,
    "email" text,
    "telefone" bigint,
    "cpf_cnpj" bigint,
    "endereco" text,
    "status" text not null default 'Ativo'::text
      );


alter table "public"."Clientes" enable row level security;


  create table "public"."Produtos" (
    "id" bigint generated by default as identity not null,
    "sku" text,
    "nome" text,
    "preco" double precision,
    "estoque" bigint,
    "status" text,
    "valor_de_custo" numeric(10,2),
    "fornecedor_id" bigint
      );


alter table "public"."Produtos" enable row level security;


  create table "public"."caixa_movimentacoes" (
    "id" bigint generated by default as identity not null,
    "caixa_id" bigint not null,
    "data_movimentacao" timestamp with time zone not null default now(),
    "tipo" public.tipo_movimentacao not null,
    "descricao" text not null,
    "valor" numeric(10,2) not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."caixa_movimentacoes" enable row level security;


  create table "public"."caixas" (
    "id" bigint generated by default as identity not null,
    "data_abertura" timestamp with time zone not null default now(),
    "valor_inicial" numeric(10,2) not null,
    "data_fechamento" timestamp with time zone,
    "valor_final_calculado" numeric(10,2),
    "valor_final_informado" numeric(10,2),
    "diferenca" numeric(10,2),
    "status" text not null default 'Aberto'::text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."caixas" enable row level security;


  create table "public"."compra_itens" (
    "id" bigint generated by default as identity not null,
    "compra_id" bigint not null,
    "produto_id" bigint not null,
    "quantidade" integer not null,
    "custo_unitario" numeric(10,2) not null
      );


alter table "public"."compra_itens" enable row level security;


  create table "public"."compras" (
    "id" bigint generated by default as identity not null,
    "data_compra" timestamp with time zone not null default now(),
    "fornecedor_id" bigint,
    "valor_total" numeric(10,2) not null,
    "status_pagamento" text not null,
    "created_at" timestamp with time zone default now(),
    "descricao" text,
    "data_vencimento" date
      );


alter table "public"."compras" enable row level security;


  create table "public"."contas_a_pagar" (
    "id" bigint generated by default as identity not null,
    "descricao" text not null,
    "valor" numeric(10,2) not null,
    "data_vencimento" date not null,
    "data_pagamento" date,
    "status" public.status_pagamento default 'Pendente'::public.status_pagamento,
    "fornecedor_id" bigint,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."contas_a_pagar" enable row level security;


  create table "public"."contas_a_receber" (
    "id" bigint generated by default as identity not null,
    "descricao" text not null,
    "valor" numeric(10,2) not null,
    "data_vencimento" date not null,
    "data_recebimento" date,
    "status" public.status_recebimento default 'Pendente'::public.status_recebimento,
    "cliente_id" bigint not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."contas_a_receber" enable row level security;


  create table "public"."fornecedores" (
    "id" bigint generated by default as identity not null,
    "nome_fantasia" text not null,
    "razao_social" text,
    "cnpj" text,
    "telefone" text,
    "email" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."fornecedores" enable row level security;


  create table "public"."funcionarios" (
    "id" bigint generated by default as identity not null,
    "nome" text not null,
    "cargo" text,
    "data_admissao" date,
    "status" text not null default 'Ativo'::text,
    "credito" numeric not null default 0,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."funcionarios" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "role" text not null default 'funcionario'::text,
    "funcionario_id" bigint,
    "full_name" text
      );


alter table "public"."profiles" enable row level security;


  create table "public"."venda_itens" (
    "id" bigint generated by default as identity not null,
    "venda_id" bigint not null,
    "produto_id" bigint not null,
    "quantidade" integer not null,
    "preco_unitario" numeric(10,2) not null,
    "preco_total" numeric(10,2) not null
      );


alter table "public"."venda_itens" enable row level security;


  create table "public"."venda_pagamentos" (
    "id" bigint generated by default as identity not null,
    "venda_id" bigint not null,
    "metodo" public.metodo_pagamento not null,
    "valor" numeric(10,2) not null
      );


alter table "public"."venda_pagamentos" enable row level security;


  create table "public"."vendas" (
    "id" bigint generated by default as identity not null,
    "data_venda" timestamp with time zone not null default now(),
    "cliente_id" bigint,
    "valor_bruto" numeric(10,2) not null,
    "desconto" numeric(10,2) default 0,
    "valor_liquido" numeric(10,2) not null,
    "status" text not null default 'Em Aberto'::text,
    "created_at" timestamp with time zone default now(),
    "status_nfe" text default 'pendente'::text
      );


alter table "public"."vendas" enable row level security;

CREATE UNIQUE INDEX "Produtos_pkey" ON public."Produtos" USING btree (id);

CREATE UNIQUE INDEX caixa_movimentacoes_pkey ON public.caixa_movimentacoes USING btree (id);

CREATE UNIQUE INDEX caixas_pkey ON public.caixas USING btree (id);

CREATE UNIQUE INDEX clientes_pkey ON public."Clientes" USING btree (id);

CREATE UNIQUE INDEX compra_itens_pkey ON public.compra_itens USING btree (id);

CREATE UNIQUE INDEX compras_pkey ON public.compras USING btree (id);

CREATE UNIQUE INDEX contas_a_pagar_pkey ON public.contas_a_pagar USING btree (id);

CREATE UNIQUE INDEX contas_a_receber_pkey ON public.contas_a_receber USING btree (id);

CREATE UNIQUE INDEX fornecedores_cnpj_key ON public.fornecedores USING btree (cnpj);

CREATE UNIQUE INDEX fornecedores_pkey ON public.fornecedores USING btree (id);

CREATE UNIQUE INDEX funcionarios_pkey ON public.funcionarios USING btree (id);

CREATE UNIQUE INDEX profiles_funcionario_id_key ON public.profiles USING btree (funcionario_id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX venda_itens_pkey ON public.venda_itens USING btree (id);

CREATE UNIQUE INDEX venda_pagamentos_pkey ON public.venda_pagamentos USING btree (id);

CREATE UNIQUE INDEX vendas_pkey ON public.vendas USING btree (id);

alter table "public"."Clientes" add constraint "clientes_pkey" PRIMARY KEY using index "clientes_pkey";

alter table "public"."Produtos" add constraint "Produtos_pkey" PRIMARY KEY using index "Produtos_pkey";

alter table "public"."caixa_movimentacoes" add constraint "caixa_movimentacoes_pkey" PRIMARY KEY using index "caixa_movimentacoes_pkey";

alter table "public"."caixas" add constraint "caixas_pkey" PRIMARY KEY using index "caixas_pkey";

alter table "public"."compra_itens" add constraint "compra_itens_pkey" PRIMARY KEY using index "compra_itens_pkey";

alter table "public"."compras" add constraint "compras_pkey" PRIMARY KEY using index "compras_pkey";

alter table "public"."contas_a_pagar" add constraint "contas_a_pagar_pkey" PRIMARY KEY using index "contas_a_pagar_pkey";

alter table "public"."contas_a_receber" add constraint "contas_a_receber_pkey" PRIMARY KEY using index "contas_a_receber_pkey";

alter table "public"."fornecedores" add constraint "fornecedores_pkey" PRIMARY KEY using index "fornecedores_pkey";

alter table "public"."funcionarios" add constraint "funcionarios_pkey" PRIMARY KEY using index "funcionarios_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."venda_itens" add constraint "venda_itens_pkey" PRIMARY KEY using index "venda_itens_pkey";

alter table "public"."venda_pagamentos" add constraint "venda_pagamentos_pkey" PRIMARY KEY using index "venda_pagamentos_pkey";

alter table "public"."vendas" add constraint "vendas_pkey" PRIMARY KEY using index "vendas_pkey";

alter table "public"."caixa_movimentacoes" add constraint "caixa_movimentacoes_caixa_id_fkey" FOREIGN KEY (caixa_id) REFERENCES public.caixas(id) ON DELETE CASCADE not valid;

alter table "public"."caixa_movimentacoes" validate constraint "caixa_movimentacoes_caixa_id_fkey";

alter table "public"."compra_itens" add constraint "compra_itens_compra_id_fkey" FOREIGN KEY (compra_id) REFERENCES public.compras(id) ON DELETE CASCADE not valid;

alter table "public"."compra_itens" validate constraint "compra_itens_compra_id_fkey";

alter table "public"."compra_itens" add constraint "compra_itens_produto_id_fkey" FOREIGN KEY (produto_id) REFERENCES public."Produtos"(id) not valid;

alter table "public"."compra_itens" validate constraint "compra_itens_produto_id_fkey";

alter table "public"."compras" add constraint "compras_fornecedor_id_fkey" FOREIGN KEY (fornecedor_id) REFERENCES public.fornecedores(id) not valid;

alter table "public"."compras" validate constraint "compras_fornecedor_id_fkey";

alter table "public"."contas_a_pagar" add constraint "contas_a_pagar_fornecedor_id_fkey" FOREIGN KEY (fornecedor_id) REFERENCES public.fornecedores(id) not valid;

alter table "public"."contas_a_pagar" validate constraint "contas_a_pagar_fornecedor_id_fkey";

alter table "public"."contas_a_receber" add constraint "contas_a_receber_cliente_id_fkey" FOREIGN KEY (cliente_id) REFERENCES public."Clientes"(id) not valid;

alter table "public"."contas_a_receber" validate constraint "contas_a_receber_cliente_id_fkey";

alter table "public"."fornecedores" add constraint "fornecedores_cnpj_key" UNIQUE using index "fornecedores_cnpj_key";

alter table "public"."profiles" add constraint "profiles_funcionario_id_fkey" FOREIGN KEY (funcionario_id) REFERENCES public.funcionarios(id) ON DELETE SET NULL not valid;

alter table "public"."profiles" validate constraint "profiles_funcionario_id_fkey";

alter table "public"."profiles" add constraint "profiles_funcionario_id_key" UNIQUE using index "profiles_funcionario_id_key";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."venda_itens" add constraint "venda_itens_produto_id_fkey" FOREIGN KEY (produto_id) REFERENCES public."Produtos"(id) not valid;

alter table "public"."venda_itens" validate constraint "venda_itens_produto_id_fkey";

alter table "public"."venda_itens" add constraint "venda_itens_venda_id_fkey" FOREIGN KEY (venda_id) REFERENCES public.vendas(id) ON DELETE CASCADE not valid;

alter table "public"."venda_itens" validate constraint "venda_itens_venda_id_fkey";

alter table "public"."venda_pagamentos" add constraint "venda_pagamentos_venda_id_fkey" FOREIGN KEY (venda_id) REFERENCES public.vendas(id) ON DELETE CASCADE not valid;

alter table "public"."venda_pagamentos" validate constraint "venda_pagamentos_venda_id_fkey";

alter table "public"."vendas" add constraint "vendas_cliente_id_fkey" FOREIGN KEY (cliente_id) REFERENCES public."Clientes"(id) not valid;

alter table "public"."vendas" validate constraint "vendas_cliente_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.atualizar_contas_vencidas()
 RETURNS void
 LANGUAGE sql
AS $function$
  update public.contas_a_pagar
  set status = 'Vencido'
  where
    status = 'Pendente' and data_vencimento < current_date;
$function$
;

CREATE OR REPLACE FUNCTION public.descontar_credito_funcionario(id_funcionario bigint, valor_desconto numeric)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  UPDATE public.funcionarios
  SET credito = credito - valor_desconto
  WHERE 
    id = id_funcionario
    AND credito >= valor_desconto; -- Condição de segurança para não deixar o crédito negativo

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Saldo de crédito insuficiente ou funcionário não encontrado.';
  END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.finalizar_venda(id_da_venda bigint)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
    item RECORD;
BEGIN
    -- 1. Itera sobre cada item da venda especificada
    FOR item IN
        SELECT produto_id, quantidade FROM public.venda_itens WHERE venda_id = id_da_venda
    LOOP
        -- 2. Dá baixa na quantidade do estoque na tabela de Produtos
        UPDATE public."Produtos"
        SET estoque = estoque - item.quantidade
        WHERE id = item.produto_id;
    END LOOP;

    -- 3. Atualiza o status da venda para 'Finalizada'
    UPDATE public.vendas
    SET status = 'Finalizada'
    WHERE id = id_da_venda;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_dashboard_stats()
 RETURNS TABLE(total_produtos bigint, valor_total_estoque numeric, produtos_estoque_baixo bigint, produtos_sem_estoque bigint)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    SELECT
        (SELECT COUNT(*) FROM "Produtos" WHERE status = 'Ativo'),
        -- A CORREÇÃO ESTÁ AQUI: Adicionamos ::NUMERIC no final da soma
        (SELECT SUM(preco * estoque)::NUMERIC FROM "Produtos" WHERE status = 'Ativo'),
        (SELECT COUNT(*) FROM "Produtos" WHERE estoque > 0 AND estoque < 10 AND status = 'Ativo'),
        (SELECT COUNT(*) FROM "Produtos" WHERE estoque = 0 AND status = 'Ativo');
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_lucratividade_periodo(data_inicio date, data_fim date)
 RETURNS TABLE(id_venda bigint, data_da_venda timestamp with time zone, cliente text, valor_da_venda numeric, custo_da_venda numeric, lucro numeric)
 LANGUAGE sql
AS $function$
  -- Usamos um CTE (WITH) para primeiro calcular o custo de cada venda
  WITH custos_por_venda AS (
    SELECT
      vi.venda_id,
      -- Soma a (quantidade * custo de cada produto) para achar o custo total da venda
      SUM(vi.quantidade * p.valor_de_custo) AS custo_total
    FROM public.venda_itens AS vi
    JOIN public."Produtos" AS p ON vi.produto_id = p.id
    -- Só considera itens que têm um valor de custo cadastrado
    WHERE p.valor_de_custo IS NOT NULL AND p.valor_de_custo > 0
    GROUP BY vi.venda_id
  )
  -- Agora, junta tudo
  SELECT
    v.id AS id_venda,
    v.data_venda AS data_da_venda,
    c.nome AS cliente,
    v.valor_liquido AS valor_da_venda,
    -- Se uma venda não teve custo (ex: produto sem custo cadastrado), considera como 0
    COALESCE(cpv.custo_total, 0) AS custo_da_venda,
    -- A mágica: Lucro = Valor da Venda - Custo da Venda
    (v.valor_liquido - COALESCE(cpv.custo_total, 0)) AS lucro
  FROM public.vendas AS v
  LEFT JOIN custos_por_venda AS cpv ON v.id = cpv.venda_id
  LEFT JOIN public."Clientes" AS c ON v.cliente_id = c.id
  WHERE v.status = 'Finalizada'
    AND v.data_venda BETWEEN data_inicio AND (data_fim + INTERVAL '1 day'); -- Pega o período inteiro
$function$
;

CREATE OR REPLACE FUNCTION public.get_or_create_cliente(nome_cliente text)
 RETURNS bigint
 LANGUAGE plpgsql
AS $function$
DECLARE
    cliente_id BIGINT;
BEGIN
    -- Tenta encontrar o cliente pelo nome (ignorando maiúsculas/minúsculas)
    SELECT id INTO cliente_id FROM public."Clientes" WHERE nome ILIKE nome_cliente LIMIT 1;

    -- Se não encontrou (a variável cliente_id está nula), cria um novo
    IF cliente_id IS NULL THEN
        INSERT INTO public."Clientes" (nome) VALUES (nome_cliente)
        RETURNING id INTO cliente_id;
    END IF;

    RETURN cliente_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_or_create_fornecedor(nome_fornecedor text)
 RETURNS bigint
 LANGUAGE plpgsql
AS $function$
DECLARE
    fornecedor_id BIGINT;
BEGIN
    SELECT id INTO fornecedor_id FROM public.fornecedores WHERE nome_fantasia ILIKE nome_fornecedor LIMIT 1;

    IF fornecedor_id IS NULL THEN
        INSERT INTO public.fornecedores (nome_fantasia) VALUES (nome_fornecedor)
        RETURNING id INTO fornecedor_id;
    END IF;

    RETURN fornecedor_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_relatorio_caixa_totalizadores(data_inicio date, data_fim date)
 RETURNS TABLE(total_vendas numeric, total_sangrias numeric, total_suprimentos numeric, diferenca_total numeric)
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN QUERY
  SELECT
    -- Soma os valores de movimentações do tipo 'VENDA'
    COALESCE(SUM(cm.valor) FILTER (WHERE cm.tipo = 'VENDA'), 0) as total_vendas,
    -- Soma os valores de movimentações do tipo 'SANGRIA'
    COALESCE(SUM(cm.valor) FILTER (WHERE cm.tipo = 'SANGRIA'), 0) as total_sangrias,
    -- Soma os valores de movimentações do tipo 'SUPRIMENTO'
    COALESCE(SUM(cm.valor) FILTER (WHERE cm.tipo = 'SUPRIMENTO'), 0) as total_suprimentos,
    -- Soma a coluna 'diferenca' da própria tabela de caixas
    (SELECT COALESCE(SUM(c.diferenca), 0) FROM public.caixas c WHERE c.data_abertura::date BETWEEN data_inicio AND data_fim) as diferenca_total
  FROM
    public.caixa_movimentacoes cm
  WHERE
    cm.created_at::date BETWEEN data_inicio AND data_fim;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_vendas_ultimos_7_dias()
 RETURNS TABLE(dia text, vendas numeric)
 LANGUAGE sql
AS $function$
  SELECT
    TO_CHAR(d.day, 'DD/MM') AS dia,
    COALESCE(SUM(v.valor_liquido), 0) AS vendas
  FROM
    -- CORREÇÃO APLICADA AQUI DENTRO
    generate_series(
      (CURRENT_DATE - INTERVAL '6 days')::date, -- Converte o início para data
      CURRENT_DATE::date,                      -- Converte o fim para data
      '1 day'
    ) AS d(day) -- Removemos o '::date' problemático daqui
  LEFT JOIN
    public.vendas AS v ON d.day = v.data_venda::date AND v.status = 'Finalizada'
  GROUP BY
    d.day
  ORDER BY
    d.day ASC;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.profiles (id)
  VALUES (new.id);
  RETURN new;
END;
$function$
;

create or replace view "public"."pessoas_venda" as  SELECT c.id,
    c.nome,
    'Cliente'::text AS tipo,
    0 AS credito_disponivel
   FROM public."Clientes" c
  WHERE (c.status = 'Ativo'::text)
UNION ALL
 SELECT f.id,
    f.nome,
    'Funcionario'::text AS tipo,
    f.credito AS credito_disponivel
   FROM public.funcionarios f
  WHERE (f.status = 'Ativo'::text);


CREATE OR REPLACE FUNCTION public.processar_entrada_de_produto(id_da_compra bigint)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
    item RECORD;
BEGIN
    -- Itera sobre cada item da compra
    FOR item IN
        SELECT produto_id, quantidade, custo_unitario FROM public.compra_itens WHERE compra_id = id_da_compra
    LOOP
        -- Atualiza o estoque E o valor de custo do produto
        UPDATE public."Produtos"
        SET 
            estoque = estoque + item.quantidade,
            valor_de_custo = item.custo_unitario
        WHERE id = item.produto_id;
    END LOOP;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.registrar_nfe_emitida(p_venda_id integer, p_status_nfe text, p_chave_acesso text, p_url_xml text, p_url_danfe text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Atualiza o status da nota na venda
    UPDATE public.vendas
    SET status_nfe = 'emitida' -- ou o status retornado pela API
    WHERE id = p_venda_id;

    -- Insere o registro da nota fiscal na tabela de notas
    INSERT INTO public.notas_fiscais (venda_id, status, chave_acesso, url_xml, url_danfe)
    VALUES (p_venda_id, p_status_nfe, p_chave_acesso, p_url_xml, p_url_danfe);
END;
$function$
;

grant delete on table "public"."Clientes" to "anon";

grant insert on table "public"."Clientes" to "anon";

grant references on table "public"."Clientes" to "anon";

grant select on table "public"."Clientes" to "anon";

grant trigger on table "public"."Clientes" to "anon";

grant truncate on table "public"."Clientes" to "anon";

grant update on table "public"."Clientes" to "anon";

grant delete on table "public"."Clientes" to "authenticated";

grant insert on table "public"."Clientes" to "authenticated";

grant references on table "public"."Clientes" to "authenticated";

grant select on table "public"."Clientes" to "authenticated";

grant trigger on table "public"."Clientes" to "authenticated";

grant truncate on table "public"."Clientes" to "authenticated";

grant update on table "public"."Clientes" to "authenticated";

grant delete on table "public"."Clientes" to "service_role";

grant insert on table "public"."Clientes" to "service_role";

grant references on table "public"."Clientes" to "service_role";

grant select on table "public"."Clientes" to "service_role";

grant trigger on table "public"."Clientes" to "service_role";

grant truncate on table "public"."Clientes" to "service_role";

grant update on table "public"."Clientes" to "service_role";

grant delete on table "public"."Produtos" to "anon";

grant insert on table "public"."Produtos" to "anon";

grant references on table "public"."Produtos" to "anon";

grant select on table "public"."Produtos" to "anon";

grant trigger on table "public"."Produtos" to "anon";

grant truncate on table "public"."Produtos" to "anon";

grant update on table "public"."Produtos" to "anon";

grant delete on table "public"."Produtos" to "authenticated";

grant insert on table "public"."Produtos" to "authenticated";

grant references on table "public"."Produtos" to "authenticated";

grant select on table "public"."Produtos" to "authenticated";

grant trigger on table "public"."Produtos" to "authenticated";

grant truncate on table "public"."Produtos" to "authenticated";

grant update on table "public"."Produtos" to "authenticated";

grant delete on table "public"."Produtos" to "service_role";

grant insert on table "public"."Produtos" to "service_role";

grant references on table "public"."Produtos" to "service_role";

grant select on table "public"."Produtos" to "service_role";

grant trigger on table "public"."Produtos" to "service_role";

grant truncate on table "public"."Produtos" to "service_role";

grant update on table "public"."Produtos" to "service_role";

grant delete on table "public"."caixa_movimentacoes" to "anon";

grant insert on table "public"."caixa_movimentacoes" to "anon";

grant references on table "public"."caixa_movimentacoes" to "anon";

grant select on table "public"."caixa_movimentacoes" to "anon";

grant trigger on table "public"."caixa_movimentacoes" to "anon";

grant truncate on table "public"."caixa_movimentacoes" to "anon";

grant update on table "public"."caixa_movimentacoes" to "anon";

grant delete on table "public"."caixa_movimentacoes" to "authenticated";

grant insert on table "public"."caixa_movimentacoes" to "authenticated";

grant references on table "public"."caixa_movimentacoes" to "authenticated";

grant select on table "public"."caixa_movimentacoes" to "authenticated";

grant trigger on table "public"."caixa_movimentacoes" to "authenticated";

grant truncate on table "public"."caixa_movimentacoes" to "authenticated";

grant update on table "public"."caixa_movimentacoes" to "authenticated";

grant delete on table "public"."caixa_movimentacoes" to "service_role";

grant insert on table "public"."caixa_movimentacoes" to "service_role";

grant references on table "public"."caixa_movimentacoes" to "service_role";

grant select on table "public"."caixa_movimentacoes" to "service_role";

grant trigger on table "public"."caixa_movimentacoes" to "service_role";

grant truncate on table "public"."caixa_movimentacoes" to "service_role";

grant update on table "public"."caixa_movimentacoes" to "service_role";

grant delete on table "public"."caixas" to "anon";

grant insert on table "public"."caixas" to "anon";

grant references on table "public"."caixas" to "anon";

grant select on table "public"."caixas" to "anon";

grant trigger on table "public"."caixas" to "anon";

grant truncate on table "public"."caixas" to "anon";

grant update on table "public"."caixas" to "anon";

grant delete on table "public"."caixas" to "authenticated";

grant insert on table "public"."caixas" to "authenticated";

grant references on table "public"."caixas" to "authenticated";

grant select on table "public"."caixas" to "authenticated";

grant trigger on table "public"."caixas" to "authenticated";

grant truncate on table "public"."caixas" to "authenticated";

grant update on table "public"."caixas" to "authenticated";

grant delete on table "public"."caixas" to "service_role";

grant insert on table "public"."caixas" to "service_role";

grant references on table "public"."caixas" to "service_role";

grant select on table "public"."caixas" to "service_role";

grant trigger on table "public"."caixas" to "service_role";

grant truncate on table "public"."caixas" to "service_role";

grant update on table "public"."caixas" to "service_role";

grant delete on table "public"."compra_itens" to "anon";

grant insert on table "public"."compra_itens" to "anon";

grant references on table "public"."compra_itens" to "anon";

grant select on table "public"."compra_itens" to "anon";

grant trigger on table "public"."compra_itens" to "anon";

grant truncate on table "public"."compra_itens" to "anon";

grant update on table "public"."compra_itens" to "anon";

grant delete on table "public"."compra_itens" to "authenticated";

grant insert on table "public"."compra_itens" to "authenticated";

grant references on table "public"."compra_itens" to "authenticated";

grant select on table "public"."compra_itens" to "authenticated";

grant trigger on table "public"."compra_itens" to "authenticated";

grant truncate on table "public"."compra_itens" to "authenticated";

grant update on table "public"."compra_itens" to "authenticated";

grant delete on table "public"."compra_itens" to "service_role";

grant insert on table "public"."compra_itens" to "service_role";

grant references on table "public"."compra_itens" to "service_role";

grant select on table "public"."compra_itens" to "service_role";

grant trigger on table "public"."compra_itens" to "service_role";

grant truncate on table "public"."compra_itens" to "service_role";

grant update on table "public"."compra_itens" to "service_role";

grant delete on table "public"."compras" to "anon";

grant insert on table "public"."compras" to "anon";

grant references on table "public"."compras" to "anon";

grant select on table "public"."compras" to "anon";

grant trigger on table "public"."compras" to "anon";

grant truncate on table "public"."compras" to "anon";

grant update on table "public"."compras" to "anon";

grant delete on table "public"."compras" to "authenticated";

grant insert on table "public"."compras" to "authenticated";

grant references on table "public"."compras" to "authenticated";

grant select on table "public"."compras" to "authenticated";

grant trigger on table "public"."compras" to "authenticated";

grant truncate on table "public"."compras" to "authenticated";

grant update on table "public"."compras" to "authenticated";

grant delete on table "public"."compras" to "service_role";

grant insert on table "public"."compras" to "service_role";

grant references on table "public"."compras" to "service_role";

grant select on table "public"."compras" to "service_role";

grant trigger on table "public"."compras" to "service_role";

grant truncate on table "public"."compras" to "service_role";

grant update on table "public"."compras" to "service_role";

grant delete on table "public"."contas_a_pagar" to "anon";

grant insert on table "public"."contas_a_pagar" to "anon";

grant references on table "public"."contas_a_pagar" to "anon";

grant select on table "public"."contas_a_pagar" to "anon";

grant trigger on table "public"."contas_a_pagar" to "anon";

grant truncate on table "public"."contas_a_pagar" to "anon";

grant update on table "public"."contas_a_pagar" to "anon";

grant delete on table "public"."contas_a_pagar" to "authenticated";

grant insert on table "public"."contas_a_pagar" to "authenticated";

grant references on table "public"."contas_a_pagar" to "authenticated";

grant select on table "public"."contas_a_pagar" to "authenticated";

grant trigger on table "public"."contas_a_pagar" to "authenticated";

grant truncate on table "public"."contas_a_pagar" to "authenticated";

grant update on table "public"."contas_a_pagar" to "authenticated";

grant delete on table "public"."contas_a_pagar" to "service_role";

grant insert on table "public"."contas_a_pagar" to "service_role";

grant references on table "public"."contas_a_pagar" to "service_role";

grant select on table "public"."contas_a_pagar" to "service_role";

grant trigger on table "public"."contas_a_pagar" to "service_role";

grant truncate on table "public"."contas_a_pagar" to "service_role";

grant update on table "public"."contas_a_pagar" to "service_role";

grant delete on table "public"."contas_a_receber" to "anon";

grant insert on table "public"."contas_a_receber" to "anon";

grant references on table "public"."contas_a_receber" to "anon";

grant select on table "public"."contas_a_receber" to "anon";

grant trigger on table "public"."contas_a_receber" to "anon";

grant truncate on table "public"."contas_a_receber" to "anon";

grant update on table "public"."contas_a_receber" to "anon";

grant delete on table "public"."contas_a_receber" to "authenticated";

grant insert on table "public"."contas_a_receber" to "authenticated";

grant references on table "public"."contas_a_receber" to "authenticated";

grant select on table "public"."contas_a_receber" to "authenticated";

grant trigger on table "public"."contas_a_receber" to "authenticated";

grant truncate on table "public"."contas_a_receber" to "authenticated";

grant update on table "public"."contas_a_receber" to "authenticated";

grant delete on table "public"."contas_a_receber" to "service_role";

grant insert on table "public"."contas_a_receber" to "service_role";

grant references on table "public"."contas_a_receber" to "service_role";

grant select on table "public"."contas_a_receber" to "service_role";

grant trigger on table "public"."contas_a_receber" to "service_role";

grant truncate on table "public"."contas_a_receber" to "service_role";

grant update on table "public"."contas_a_receber" to "service_role";

grant delete on table "public"."fornecedores" to "anon";

grant insert on table "public"."fornecedores" to "anon";

grant references on table "public"."fornecedores" to "anon";

grant select on table "public"."fornecedores" to "anon";

grant trigger on table "public"."fornecedores" to "anon";

grant truncate on table "public"."fornecedores" to "anon";

grant update on table "public"."fornecedores" to "anon";

grant delete on table "public"."fornecedores" to "authenticated";

grant insert on table "public"."fornecedores" to "authenticated";

grant references on table "public"."fornecedores" to "authenticated";

grant select on table "public"."fornecedores" to "authenticated";

grant trigger on table "public"."fornecedores" to "authenticated";

grant truncate on table "public"."fornecedores" to "authenticated";

grant update on table "public"."fornecedores" to "authenticated";

grant delete on table "public"."fornecedores" to "service_role";

grant insert on table "public"."fornecedores" to "service_role";

grant references on table "public"."fornecedores" to "service_role";

grant select on table "public"."fornecedores" to "service_role";

grant trigger on table "public"."fornecedores" to "service_role";

grant truncate on table "public"."fornecedores" to "service_role";

grant update on table "public"."fornecedores" to "service_role";

grant delete on table "public"."funcionarios" to "anon";

grant insert on table "public"."funcionarios" to "anon";

grant references on table "public"."funcionarios" to "anon";

grant select on table "public"."funcionarios" to "anon";

grant trigger on table "public"."funcionarios" to "anon";

grant truncate on table "public"."funcionarios" to "anon";

grant update on table "public"."funcionarios" to "anon";

grant delete on table "public"."funcionarios" to "authenticated";

grant insert on table "public"."funcionarios" to "authenticated";

grant references on table "public"."funcionarios" to "authenticated";

grant select on table "public"."funcionarios" to "authenticated";

grant trigger on table "public"."funcionarios" to "authenticated";

grant truncate on table "public"."funcionarios" to "authenticated";

grant update on table "public"."funcionarios" to "authenticated";

grant delete on table "public"."funcionarios" to "service_role";

grant insert on table "public"."funcionarios" to "service_role";

grant references on table "public"."funcionarios" to "service_role";

grant select on table "public"."funcionarios" to "service_role";

grant trigger on table "public"."funcionarios" to "service_role";

grant truncate on table "public"."funcionarios" to "service_role";

grant update on table "public"."funcionarios" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."venda_itens" to "anon";

grant insert on table "public"."venda_itens" to "anon";

grant references on table "public"."venda_itens" to "anon";

grant select on table "public"."venda_itens" to "anon";

grant trigger on table "public"."venda_itens" to "anon";

grant truncate on table "public"."venda_itens" to "anon";

grant update on table "public"."venda_itens" to "anon";

grant delete on table "public"."venda_itens" to "authenticated";

grant insert on table "public"."venda_itens" to "authenticated";

grant references on table "public"."venda_itens" to "authenticated";

grant select on table "public"."venda_itens" to "authenticated";

grant trigger on table "public"."venda_itens" to "authenticated";

grant truncate on table "public"."venda_itens" to "authenticated";

grant update on table "public"."venda_itens" to "authenticated";

grant delete on table "public"."venda_itens" to "service_role";

grant insert on table "public"."venda_itens" to "service_role";

grant references on table "public"."venda_itens" to "service_role";

grant select on table "public"."venda_itens" to "service_role";

grant trigger on table "public"."venda_itens" to "service_role";

grant truncate on table "public"."venda_itens" to "service_role";

grant update on table "public"."venda_itens" to "service_role";

grant delete on table "public"."venda_pagamentos" to "anon";

grant insert on table "public"."venda_pagamentos" to "anon";

grant references on table "public"."venda_pagamentos" to "anon";

grant select on table "public"."venda_pagamentos" to "anon";

grant trigger on table "public"."venda_pagamentos" to "anon";

grant truncate on table "public"."venda_pagamentos" to "anon";

grant update on table "public"."venda_pagamentos" to "anon";

grant delete on table "public"."venda_pagamentos" to "authenticated";

grant insert on table "public"."venda_pagamentos" to "authenticated";

grant references on table "public"."venda_pagamentos" to "authenticated";

grant select on table "public"."venda_pagamentos" to "authenticated";

grant trigger on table "public"."venda_pagamentos" to "authenticated";

grant truncate on table "public"."venda_pagamentos" to "authenticated";

grant update on table "public"."venda_pagamentos" to "authenticated";

grant delete on table "public"."venda_pagamentos" to "service_role";

grant insert on table "public"."venda_pagamentos" to "service_role";

grant references on table "public"."venda_pagamentos" to "service_role";

grant select on table "public"."venda_pagamentos" to "service_role";

grant trigger on table "public"."venda_pagamentos" to "service_role";

grant truncate on table "public"."venda_pagamentos" to "service_role";

grant update on table "public"."venda_pagamentos" to "service_role";

grant delete on table "public"."vendas" to "anon";

grant insert on table "public"."vendas" to "anon";

grant references on table "public"."vendas" to "anon";

grant select on table "public"."vendas" to "anon";

grant trigger on table "public"."vendas" to "anon";

grant truncate on table "public"."vendas" to "anon";

grant update on table "public"."vendas" to "anon";

grant delete on table "public"."vendas" to "authenticated";

grant insert on table "public"."vendas" to "authenticated";

grant references on table "public"."vendas" to "authenticated";

grant select on table "public"."vendas" to "authenticated";

grant trigger on table "public"."vendas" to "authenticated";

grant truncate on table "public"."vendas" to "authenticated";

grant update on table "public"."vendas" to "authenticated";

grant delete on table "public"."vendas" to "service_role";

grant insert on table "public"."vendas" to "service_role";

grant references on table "public"."vendas" to "service_role";

grant select on table "public"."vendas" to "service_role";

grant trigger on table "public"."vendas" to "service_role";

grant truncate on table "public"."vendas" to "service_role";

grant update on table "public"."vendas" to "service_role";


  create policy "Enable insert for authenticated users only"
  on "public"."Clientes"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."Clientes"
  as permissive
  for select
  to public
using (true);



  create policy "Usuários logados podem gerenciar clientes"
  on "public"."Clientes"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Enable insert for authenticated users only"
  on "public"."Produtos"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."Produtos"
  as permissive
  for select
  to public
using (true);



  create policy "Usuários logados podem gerenciar produtos"
  on "public"."Produtos"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Usuários autenticados podem gerenciar movimentações"
  on "public"."caixa_movimentacoes"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Usuários autenticados podem gerenciar caixas"
  on "public"."caixas"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Usuários autenticados podem gerenciar itens de compra"
  on "public"."compra_itens"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Usuários autenticados podem gerenciar compras"
  on "public"."compras"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Usuários autenticados podem gerenciar contas a pagar"
  on "public"."contas_a_pagar"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Usuários autenticados podem gerenciar contas a receber"
  on "public"."contas_a_receber"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Usuários autenticados podem gerenciar fornecedores"
  on "public"."fornecedores"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Usuários autenticados podem gerenciar funcionários"
  on "public"."funcionarios"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Usuários podem atualizar seus próprios perfis."
  on "public"."profiles"
  as permissive
  for update
  to authenticated
using ((auth.uid() = id))
with check ((auth.uid() = id));



  create policy "Usuários podem ver seus próprios perfis."
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using ((auth.uid() = id));



  create policy "Usuários autenticados podem gerenciar itens de venda"
  on "public"."venda_itens"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Usuários autenticados podem gerenciar pagamentos de venda"
  on "public"."venda_pagamentos"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Usuários autenticados podem gerenciar vendas"
  on "public"."vendas"
  as permissive
  for all
  to authenticated
using (true)
with check (true);


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


